stages:  
  - test
  - build

lint-test-job:
  tags:
    - runner
  stage: test
  image: golangci/golangci-lint:latest
  script:
    - echo "Started linting."
    - golangci-lint run
    - echo "Linting finished"

build-job:
  tags:
    - runner
  stage: build
  script:
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/e-com-shop/backend/eshop-products-ms .
    - docker push registry.gitlab.com/e-com-shop/backend/eshop-products-ms
