stages:  
  - test
  - build

lint-test-job:
  stage: test
  image: golang:1.21.6
  cache:
    paths:
      - .cache
  script:
    - go mod download
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - golangci-lint run --timeout=600s
    - echo "Linting finished."


build-job:
  image: docker:latest
  stage: build
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.gitlab.com
    - docker build -t registry.gitlab.com/e-com-shop/backend/eshop-products-ms .
    - docker push registry.gitlab.com/e-com-shop/backend/eshop-products-ms
