stages:  
  - test
  - build

lint-test-job:
  stage: test
  image: golang:1.21.6
  cache:
    key: ${CI_COMMIT_REF_SLUG}-go-modules
    paths:
      - go.mod
      - go.sum
      - ${GOPATH}/pkg/mod
  before_script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
  script:
    - go mod download
    - golangci-lint run --timeout=600s
    - echo "Linting finished."


build-job:
  image: docker:latest
  stage: build
  script:
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/e-com-shop/backend/eshop-products-ms .
    - docker push registry.gitlab.com/e-com-shop/backend/eshop-products-ms
