stages:  
  - test
  - build

lint-test-job:
  stage: test
  image: golang:1.21.6
  before_script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2golangci-lint --version
  script:
    - golangci-lint run
    - echo "Linting finished."

build-job:
  stage: build
  script:
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/e-com-shop/backend/eshop-products-ms .
    - docker push registry.gitlab.com/e-com-shop/backend/eshop-products-ms
