env: local
database:
  host: postgres
  port: 5432
  user: user
  pass: pass
  name: test
jwt:
  secret: secret
  ttl: 3600
grpc:
  port: 9090
redis:
  host: redis
  port: 6379
  pass: pass
  db: 0
loki:
  host: loki
  port: 3100
minio:
  host: minio
  port: 9000
  access_key: username
  secret_key: password
  use_ssl: false
  bucket: products